config/routes.rb
Rails.application.routes.draw do
  scope module: :users do
    scope path: 'salasanan_uusiminen' do
      get '/' => 'password_resets#new', as: 'new_password_reset'
      post 'generoi' => 'password_resets#generate_token', as: 'generate_token_for_password_reset'
      get 'kirjoita' => 'password_resets#type_token', as: 'type_token_for_password_reset'
      get 'luo_uusi/:id/:token' => 'password_resets#typed_token', as: 'email_link_for_typed_token_for_password_reset'
      post 'luo_uusi' => 'password_resets#typed_token', as: 'typed_token_for_password_reset'
      post 'uusi_luotu' => 'password_resets#typed_new_password_for_password_reset', as: 'typed_new_password_for_password_reset'
      get '/:custom_path' => 'password_resets#new'
    end
  end
end

app/models/user/password_reset.rb
class User::PasswordReset < ApplicationRecord
  self.table_name = 'user_password_resets'
  
  belongs_to :user, optional: true
  
  def self.new_for_email(email)
    return false unless email.present?
    users = User.respond_to?(:custom_where_by) ? User.custom_where_by(email: email) : User.where(email: email)
    if users.exists?
      user = users.order(id: :asc).first
      self.where(user_id: user.id).delete_all if self.where(user_id: user.id).exists?
      token = new_token
      digest = digest(token)
      password_reset = new
      password_reset.user = user
      password_reset.reset_digest = digest
      password_reset.save
      
      domain = Rails.application.config.action_controller.default_url_options[:host]
      
      UserPasswordResetMailer.with(user: user, email: user.email, reset_token: token,
        change_link: Rails.application.routes.url_helpers.email_link_for_typed_token_for_password_reset_url(user, token),
        domain: domain
      ).password_reset_email.deliver_now
      
      if (send_sms = UserPasswordResetSystem.settings[:send_sms]) && user.phone.present?
        send_sms[to: user.phone, message: I18n.t("user.password_reset.info_sms_about_asked_reset", domain: domain)]
      end
      
      return true
    else
      return false
    end
  end
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
 end
   
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def self.token_allowed(**options)
    if self.where(user_id: options[:user_id]).exists?
      correct_digest = self.where(user_id: options[:user_id]).last.reset_digest
      return BCrypt::Password.new(correct_digest) == options[:token]
    else
      return false
    end
  end

  def self.delete_token_for_user(user_id)
    self.where(user_id: user_id).delete_all if self.where(user_id: user_id).exists?
  end
  
end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < ApplicationController

  skip_before_action :require_login rescue nil
  
  def new
    skip_authorization
  end
  
  def generate_token
    skip_authorization
    User::PasswordReset.new_for_email(params[:email])
    flash_notice
    flash.discard(:notice)
    render :type_token
  end

  def type_token
    skip_authorization
  end
  
  def typed_token
    skip_authorization
    query = if params[:email].present?
      { email: params[:email] }
    elsif params[:id].present?
      { id: params[:id] }
    end
    if query
      users = User.respond_to?(:custom_where_by) ? User.custom_where_by(**query) : User.where(**query)
      user = users.order(id: :asc).first
      if user.present?
        user_id = user.id
        if User::PasswordReset.token_allowed(token: params[:token], user_id: user_id)
          flash_success
          @user = user
          render :new_password
          return
        end
      end
    end
    flash_error
    render :type_token
  end
  
  def typed_new_password_for_password_reset
    skip_authorization
    if params[:id].present?
      user_id = params[:id]
    else
      users = User.respond_to?(:custom_where_by) ? User.custom_where_by(email: params[:email]) : User.where(email: params[:email])
      user_id = users.order(id: :asc).first.id
    end
    if User::PasswordReset.token_allowed(token: params[:token], user_id: user_id)
      user = User.find user_id
      if user.update(user_password_params)
        User::PasswordReset.delete_token_for_user(user_id)
        unless UserPasswordResetSystem.settings[:run_after_password_reset_success]
          flash_success
          redirect_to root_path
        else
          after_password_reset_success user
        end
      else
        @user = user
        render :new_password
      end
    else
      flash_error '.wrong_code'
      redirect_to type_token_for_password_reset_path
    end
  end
  
  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
  
end

app/views/users/password_resets/new.html.erb
<%= form_tag({ action: :generate_token }, { class: "general" }) do %>
  <%= text_field_tag :email, nil, placeholder: t(".email") %>
  <%= submit_tag t(".send_code") %>
<% end %>

app/views/users/password_resets/new_password.html.erb
<%= list_errors @user %>
<%= form_for @user, url: { action: :typed_new_password_for_password_reset }, method: :post, html: { class: "general" } do |f| %>
  <% unless UserPasswordResetSystem.settings[:hide_username] %>
    <%= f.text_field :username, disabled: true, placeholder: User.human_attribute_name(:username) %>
  <% end %>
  <%= f.password_field :password, placeholder: t(".new_password") %>
  <%= f.password_field :password_confirmation, placeholder: t(".new_password_confirmation") %>
  <%= hidden_field_tag :token, params[:token] %>
  <%= hidden_field_tag :email, params[:email] %>
  <%= hidden_field_tag :id, params[:id] %>
  <%= submit_tag t(".save") %>
<% end %>

app/views/users/password_resets/type_token.html.erb
<%= form_tag typed_token_for_password_reset_path, class: "general" do %>
  <%= text_field_tag :token, nil, placeholder: t(".token") %>
  <%= hidden_field_tag :email, params[:email] %>
  <%= submit_tag t(".send") %>
<% end %>